#!/bin/bash
Executable_PATH="`dirname "${0}"`"
Executable_BIN="`dirname "${0}"`"/Preview_

export DYLD_FORCE_FLAT_NAMESPACE=1
export DYLD_INSERT_LIBRARIES="${Executable_PATH}/libPatch.dylib"
"$Executable_BIN"
